[tool.poetry]
name = "hw-8"
version = "0.1.0"
description = ""
authors = ["Olena Maliarenko"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
